### ISSUE TITLE
why reference application if logs are cluster wide

### ISSUE THREAD

**Issue by EvertonSA** [CiscoDevNet/ContainerLabs#23]
https://github.com/CiscoDevNet/ContainerLabs/blob/8d94794df8e3c29d94823ce9169b9414af7e4c4e/Labs/Lab-2.3-Analytics/logging/agent-config.yaml#L4

as far as I understand, the log agent is deployed cluster wide and is instrumented bellow an app abstraction. 

this instrumentation enforces that:

applications are bounded to clusters

OR

applications are running in application specific node pools

this instrumentation does not work for:

general clusters with multiple applications running in common node groups.

can someone please elaborate if my conclusions are correct?

**Comment by jeffaholmes** [comment]
Everton
The agent-config.yaml is for an appd app agent (not logging agent) running in a pod that's generating logs for the logging agent (part of an internal lab scenario), hence the appd app-specific settings, including app and tier name.

We have some more specific docs on options for deploying log agent here: https://docs.appdynamics.com/appd/22.x/latest/en/analytics/deploy-analytics-with-the-analytics-agent/install-agent-side-components-in-kubernetes

Also, doc ref for use of config map to set appd params, which could include analytics agent settings: :https://docs.appdynamics.com/display/PRMY22/Install+the+Node.js+Agent+in+Containers#InstalltheNode.jsAgentinContainers-set-envars
Install the Node.js Agent in Containers - AppDynamics<https://docs.appdynamics.com/display/PRMY22/Install+the+Node.js+Agent+in+Containers#InstalltheNode.jsAgentinContainers-set-envars>
This option uses Kubernetes init containers to copy the Node.js Agent binaries into the application container when the application starts up. It assumes that the application image is built without any Node.js Agent binaries and that a second init container image is built which contains the Node.js Agent binaries.
docs.appdynamics.com



Jeff Holmes | Cloud Domain Architect | Field Architecture
Mobile 503-740-2568
AppDynamics
The Application Intelligence Company
Watch our video<https://player.vimeo.com/external/137403850.hd.mp4?s=14c2030b6f8bc436aebba39b1b89ef03&profile_id=119>  |  Try our FREE Trial<https://portal.appdynamics.com/account/signup/signupForm>  |  Twitter<https://twitter.com/appdynamics>  |  LinkedIn<https://www.linkedin.com/company/appdynamics>  |  appdynamics.com<https://www.appdynamics.com/>
________________________________
From: Everton Seiei Arakaki ***@***.***>
Sent: Tuesday, August 9, 2022 4:07 AM
To: CiscoDevNet/ContainerLabs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CiscoDevNet/ContainerLabs] why reference application if logs are cluster wide (Issue #23)


https://github.com/CiscoDevNet/ContainerLabs/blob/8d94794df8e3c29d94823ce9169b9414af7e4c4e/Labs/Lab-2.3-Analytics/logging/agent-config.yaml#L4

as far as I understand, the log agent is deployed cluster wide and is instrumented bellow an app abstraction.

this instrumentation enforces that:

applications are bounded to clusters

OR

applications are running in application specific node pools

this instrumentation does not work for:

general clusters with multiple applications running in common node groups.

can someone please elaborate if my conclusions are correct?
